[mainConfig]
appName = "aiplatform"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "emfevnnlawazdhhc"
email = "2077317639@qq.com"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "532948"
databaseName = "aiplatform"
charset =  "utf8mb4"

[jwtConfig]
 expire_duration= 8760
 issuer= "huanheart"
 subject= "aiplatform"
 key= "aiplatform-v1"

 [rabbitmqConfig]
  host= "rabbitmq"
  port= 5672
  username= "root"
  password= "123456"
  vhost= "/"

 [ragModelConfig]
  embeddingModel= "text-embedding-v4"
  chatModelName="qwen-turbo"
  docDir = "./docs"
  baseUrl="https://dashscope.aliyuncs.com/compatible-mode/v1"
  dimension=1024
  chunkSize=800
  chunkOverlap=150
  topK=5

  [voiceServiceConfig]
  voiceServiceApiKey = "baiduApiKey"
  voiceServiceSecretKey ="baiduSecretKey"
